name: Validate XML Code for Errors

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes main

jobs:
  validate-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate XML
        uses: ChristophWurst/xmllint-action@v1.2.1
        with:
          xml-file: edition.xml
          xml-schema-file: ./TEI/tei_all.rng
          xml-schema-type: relaxng
